//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConquiánServidor.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConquiánServidor.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al procesar la acción del juego..
        /// </summary>
        public static string ErrorGameAction {
            get {
                return ResourceManager.GetString("ErrorGameAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El movimiento intentado no es válido..
        /// </summary>
        public static string ErrorGameInvalidMove {
            get {
                return ResourceManager.GetString("ErrorGameInvalidMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La partida solicitada no existe o ha finalizado..
        /// </summary>
        public static string ErrorGameNotFound {
            get {
                return ResourceManager.GetString("ErrorGameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es tu turno para realizar esta acción..
        /// </summary>
        public static string ErrorGameNotYourTurn {
            get {
                return ResourceManager.GetString("ErrorGameNotYourTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo enviar el correo electrónico a {0}..
        /// </summary>
        public static string ErrorGuestInviteEmailFailed {
            get {
                return ResourceManager.GetString("ErrorGuestInviteEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credenciales inválidas.
        /// </summary>
        public static string ErrorInvalidCredentials {
            get {
                return ResourceManager.GetString("ErrorInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No cuenta con una invitación..
        /// </summary>
        public static string ErrorInvalidInvitation {
            get {
                return ResourceManager.GetString("ErrorInvalidInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al intentar enviar la invitación..
        /// </summary>
        public static string ErrorInvitationFailed {
            get {
                return ResourceManager.GetString("ErrorInvitationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al realizar la operación en el lobby.
        /// </summary>
        public static string ErrorLobbyAction {
            get {
                return ResourceManager.GetString("ErrorLobbyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sala está llena o en juego..
        /// </summary>
        public static string ErrorLobbyFull {
            get {
                return ResourceManager.GetString("ErrorLobbyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario anfitrión no se encuentra..
        /// </summary>
        public static string ErrorLobbyHostNotFound {
            get {
                return ResourceManager.GetString("ErrorLobbyHostNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes seleccionar un modo de juego antes de iniciar..
        /// </summary>
        public static string ErrorLobbyNoGamemode {
            get {
                return ResourceManager.GetString("ErrorLobbyNoGamemode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay suficientes jugadores para iniciar..
        /// </summary>
        public static string ErrorLobbyNotEnoughPlayers {
            get {
                return ResourceManager.GetString("ErrorLobbyNotEnoughPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sala no existe o ya ha cerrado..
        /// </summary>
        public static string ErrorLobbyNotFound {
            get {
                return ResourceManager.GetString("ErrorLobbyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este nombre de usuario ya existe.
        /// </summary>
        public static string ErrorNicknameExists {
            get {
                return ResourceManager.GetString("ErrorNicknameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes expulsar debido a que no eres el host.
        /// </summary>
        public static string ErrorNotLobbyHost {
            get {
                return ResourceManager.GetString("ErrorNotLobbyHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador se encuentra desconectado..
        /// </summary>
        public static string ErrorPlayerOffline {
            get {
                return ResourceManager.GetString("ErrorPlayerOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en el servicio Presence..
        /// </summary>
        public static string ErrorPresenceAction {
            get {
                return ResourceManager.GetString("ErrorPresenceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este correo ya está registrado, por favor inicie sesión.
        /// </summary>
        public static string ErrorRegisteredMail {
            get {
                return ResourceManager.GetString("ErrorRegisteredMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya cuenta con una sesión activa, por favor cierre la sesión activa para poder abrir una nueva.
        /// </summary>
        public static string ErrorSessionActive {
            get {
                return ResourceManager.GetString("ErrorSessionActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta invitación ya ha sido utilizada..
        /// </summary>
        public static string ErrorUsedInvitation {
            get {
                return ResourceManager.GetString("ErrorUsedInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no encontrado.
        /// </summary>
        public static string ErrorUserNotFound {
            get {
                return ResourceManager.GetString("ErrorUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de verificación es incorrecto.
        /// </summary>
        public static string ErrorVerificationCodeIncorrect {
            get {
                return ResourceManager.GetString("ErrorVerificationCodeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes unirte a este lobby porque fuiste expulsado..
        /// </summary>
        public static string ErrorYouAreKicked {
            get {
                return ResourceManager.GetString("ErrorYouAreKicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de validación de entidad (DbEntityValidationException): {0}.
        /// </summary>
        public static string GlobalDbEntityValidationError {
            get {
                return ResourceManager.GetString("GlobalDbEntityValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar en BD (DbUpdateException): {0}.
        /// </summary>
        public static string GlobalDbUpdateError {
            get {
                return ResourceManager.GetString("GlobalDbUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al enviar el correo, vuelve a intentarlo más tarde.
        /// </summary>
        public static string GlobalSmtpError {
            get {
                return ResourceManager.GetString("GlobalSmtpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al conectar con la base de datos.
        /// </summary>
        public static string GlobalSqlError {
            get {
                return ResourceManager.GetString("GlobalSqlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Estás invitado a una partida de Conquián!.
        /// </summary>
        public static string GuestEmailSubject {
            get {
                return ResourceManager.GetString("GuestEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error interno del servidor..
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intento de autenticación para: {0}.
        /// </summary>
        public static string LogAuthLogicAuthAttempt {
            get {
                return ResourceManager.GetString("LogAuthLogicAuthAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autenticación fallida para: {0} (Usuario no encontrado o contraseña incorrecta).
        /// </summary>
        public static string LogAuthLogicAuthFailed {
            get {
                return ResourceManager.GetString("LogAuthLogicAuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador autenticado exitosamente: {0} (ID: {1}).
        /// </summary>
        public static string LogAuthLogicAuthSuccess {
            get {
                return ResourceManager.GetString("LogAuthLogicAuthSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al borrar jugador temporal (DbUpdateException): {0}.
        /// </summary>
        public static string LogAuthLogicDeleteTempDbUpdateError {
            get {
                return ResourceManager.GetString("LogAuthLogicDeleteTempDbUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se eliminó jugador temporal {0} (no encontrado o ya registrado)..
        /// </summary>
        public static string LogAuthLogicDeleteTempNotFound {
            get {
                return ResourceManager.GetString("LogAuthLogicDeleteTempNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de SQL al borrar jugador temporal (SqlException): {0}.
        /// </summary>
        public static string LogAuthLogicDeleteTempSqlError {
            get {
                return ResourceManager.GetString("LogAuthLogicDeleteTempSqlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador temporal eliminado: {0}.
        /// </summary>
        public static string LogAuthLogicDeleteTempSuccess {
            get {
                return ResourceManager.GetString("LogAuthLogicDeleteTempSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error inesperado en DeleteTemporaryPlayerAsync: {0}.
        /// </summary>
        public static string LogAuthLogicDeleteTempUnexpectedError {
            get {
                return ResourceManager.GetString("LogAuthLogicDeleteTempUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al actualizar token en BD (DbUpdateException): {0}.
        /// </summary>
        public static string LogAuthLogicGenTokenDbUpdateError {
            get {
                return ResourceManager.GetString("LogAuthLogicGenTokenDbUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se generó token para {0}: Jugador no encontrado o sin contraseña..
        /// </summary>
        public static string LogAuthLogicGenTokenNotFound {
            get {
                return ResourceManager.GetString("LogAuthLogicGenTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de SQL en GenerateAndStoreRecoveryTokenAsync (SqlException): {0}.
        /// </summary>
        public static string LogAuthLogicGenTokenSqlError {
            get {
                return ResourceManager.GetString("LogAuthLogicGenTokenSqlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Token de recuperación generado para: {0}.
        /// </summary>
        public static string LogAuthLogicGenTokenSuccess {
            get {
                return ResourceManager.GetString("LogAuthLogicGenTokenSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error inesperado en GenerateAndStoreRecoveryTokenAsync: {0}.
        /// </summary>
        public static string LogAuthLogicGenTokenUnexpectedError {
            get {
                return ResourceManager.GetString("LogAuthLogicGenTokenUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al enviar correo de recuperación (SmtpException): {0}.
        /// </summary>
        public static string LogAuthLogicPassRecoverySmtpError {
            get {
                return ResourceManager.GetString("LogAuthLogicPassRecoverySmtpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email de recuperación enviado a: {0}.
        /// </summary>
        public static string LogAuthLogicPassRecoverySuccess {
            get {
                return ResourceManager.GetString("LogAuthLogicPassRecoverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de recuperación de contraseña fallida para {0}: No se pudo generar el token..
        /// </summary>
        public static string LogAuthLogicPassRecoveryTokenFailed {
            get {
                return ResourceManager.GetString("LogAuthLogicPassRecoveryTokenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error inesperado en solicitud de recuperación: {0}.
        /// </summary>
        public static string LogAuthLogicPassRecoveryUnexpectedError {
            get {
                return ResourceManager.GetString("LogAuthLogicPassRecoveryUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al reiniciar contraseña en BD (DbUpdateException): {0}.
        /// </summary>
        public static string LogAuthLogicPassResetDbUpdateError {
            get {
                return ResourceManager.GetString("LogAuthLogicPassResetDbUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reinicio de contraseña fallido para {0}: Contraseña no válida..
        /// </summary>
        public static string LogAuthLogicPassResetInvalidPassword {
            get {
                return ResourceManager.GetString("LogAuthLogicPassResetInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reinicio de contraseña fallido para {0}: Jugador no encontrado (post-validación)..
        /// </summary>
        public static string LogAuthLogicPassResetPlayerNotFound {
            get {
                return ResourceManager.GetString("LogAuthLogicPassResetPlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de SQL al reiniciar contraseña (SqlException): {0}.
        /// </summary>
        public static string LogAuthLogicPassResetSqlError {
            get {
                return ResourceManager.GetString("LogAuthLogicPassResetSqlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña reiniciada exitosamente para: {0}.
        /// </summary>
        public static string LogAuthLogicPassResetSuccess {
            get {
                return ResourceManager.GetString("LogAuthLogicPassResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reinicio de contraseña fallido para {0}: Token inválido o expirado..
        /// </summary>
        public static string LogAuthLogicPassResetTokenFailed {
            get {
                return ResourceManager.GetString("LogAuthLogicPassResetTokenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error inesperado al reiniciar contraseña: {0}.
        /// </summary>
        public static string LogAuthLogicPassResetUnexpectedError {
            get {
                return ResourceManager.GetString("LogAuthLogicPassResetUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intento de registro fallido para {0}: El nickname {1} ya existe..
        /// </summary>
        public static string LogAuthLogicRegisterNicknameExists {
            get {
                return ResourceManager.GetString("LogAuthLogicRegisterNicknameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error inesperado en RegisterPlayerAsync: {0}.
        /// </summary>
        public static string LogAuthLogicRegisterPlayerUnexpectedError {
            get {
                return ResourceManager.GetString("LogAuthLogicRegisterPlayerUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador registrado exitosamente: {0} (Email: {1}).
        /// </summary>
        public static string LogAuthLogicRegisterSuccess {
            get {
                return ResourceManager.GetString("LogAuthLogicRegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validación de registro fallida para {0}: {1}.
        /// </summary>
        public static string LogAuthLogicRegisterValidationFailed {
            get {
                return ResourceManager.GetString("LogAuthLogicRegisterValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar código en BD (DbUpdateException): {0}.
        /// </summary>
        public static string LogAuthLogicSendCodeDbUpdateError {
            get {
                return ResourceManager.GetString("LogAuthLogicSendCodeDbUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de validación de entidad en SendVerificationCodeAsync (DbEntityValidationException): {0}.
        /// </summary>
        public static string LogAuthLogicSendCodeEfValidationError {
            get {
                return ResourceManager.GetString("LogAuthLogicSendCodeEfValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intento de enviar código de verificación fallido: Email {0} ya existe..
        /// </summary>
        public static string LogAuthLogicSendCodeEmailExists {
            get {
                return ResourceManager.GetString("LogAuthLogicSendCodeEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intento de enviar código de verificación fallido: Email inválido {0}.
        /// </summary>
        public static string LogAuthLogicSendCodeInvalidEmail {
            get {
                return ResourceManager.GetString("LogAuthLogicSendCodeInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de SQL en SendVerificationCodeAsync (SqlException): {0}.
        /// </summary>
        public static string LogAuthLogicSendCodeSqlError {
            get {
                return ResourceManager.GetString("LogAuthLogicSendCodeSqlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de verificación enviado a: {0}.
        /// </summary>
        public static string LogAuthLogicSendCodeSuccess {
            get {
                return ResourceManager.GetString("LogAuthLogicSendCodeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error inesperado en SendVerificationCodeAsync: {0}.
        /// </summary>
        public static string LogAuthLogicSendCodeUnexpectedError {
            get {
                return ResourceManager.GetString("LogAuthLogicSendCodeUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intento de cierre de sesión para ID: {0}.
        /// </summary>
        public static string LogAuthLogicSignOutAttempt {
            get {
                return ResourceManager.GetString("LogAuthLogicSignOutAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador {0} cerró sesión exitosamente..
        /// </summary>
        public static string LogAuthLogicSignOutSuccess {
            get {
                return ResourceManager.GetString("LogAuthLogicSignOutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificación de código fallida para: {0} (código incorrecto o expirado).
        /// </summary>
        public static string LogAuthLogicVerifyCodeFailed {
            get {
                return ResourceManager.GetString("LogAuthLogicVerifyCodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de SQL al verificar el código (SqlException): {0}.
        /// </summary>
        public static string LogAuthLogicVerifyCodeSqlError {
            get {
                return ResourceManager.GetString("LogAuthLogicVerifyCodeSqlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código verificado exitosamente para: {0}.
        /// </summary>
        public static string LogAuthLogicVerifyCodeSuccess {
            get {
                return ResourceManager.GetString("LogAuthLogicVerifyCodeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error inesperado al verificar el código: {0}.
        /// </summary>
        public static string LogAuthLogicVerifyCodeUnexpectedError {
            get {
                return ResourceManager.GetString("LogAuthLogicVerifyCodeUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción fallida en juego {0} por jugador {1}: {2}..
        /// </summary>
        public static string LogGameActionFailed {
            get {
                return ResourceManager.GetString("LogGameActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al transmitir la actualización a todos los jugadores..
        /// </summary>
        public static string LogGameBroadcastError {
            get {
                return ResourceManager.GetString("LogGameBroadcastError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al enviar notificación al jugador {0}. Se eliminará de la sesión..
        /// </summary>
        public static string LogGameCallbackError {
            get {
                return ResourceManager.GetString("LogGameCallbackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador {0} tomó carta del mazo en la sala {1}.
        /// </summary>
        public static string LogGameDrawDeckSuccess {
            get {
                return ResourceManager.GetString("LogGameDrawDeckSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador {0} se unió a la sala {1}..
        /// </summary>
        public static string LogGameJoinSuccess {
            get {
                return ResourceManager.GetString("LogGameJoinSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador {0} jugó cartas en la sala {1}..
        /// </summary>
        public static string LogGamePlayCardSuccess {
            get {
                return ResourceManager.GetString("LogGamePlayCardSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitación de huésped enviada a {0} para la sala {1}..
        /// </summary>
        public static string LogGuestInviteSent {
            get {
                return ResourceManager.GetString("LogGuestInviteSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo al entregar invitación al jugador {0}..
        /// </summary>
        public static string LogInvitationDeliveryFailed {
            get {
                return ResourceManager.GetString("LogInvitationDeliveryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitación enviada de {0} a {1} para sala {2}..
        /// </summary>
        public static string LogInvitationSent {
            get {
                return ResourceManager.GetString("LogInvitationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador {0} se suscribió a notificaciones de invitación..
        /// </summary>
        public static string LogInvitationSubscribed {
            get {
                return ResourceManager.GetString("LogInvitationSubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador {0} se desuscribió de notificaciones..
        /// </summary>
        public static string LogInvitationUnsubscribed {
            get {
                return ResourceManager.GetString("LogInvitationUnsubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby {0} creado por el anfitrión {1}.
        /// </summary>
        public static string LogLobbyCreated {
            get {
                return ResourceManager.GetString("LogLobbyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modo de juego actualizado en lobby {0} a {1}.
        /// </summary>
        public static string LogLobbyGamemodeChanged {
            get {
                return ResourceManager.GetString("LogLobbyGamemodeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juego iniciado en lobby {0}.
        /// </summary>
        public static string LogLobbyGameStarted {
            get {
                return ResourceManager.GetString("LogLobbyGameStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador {0} se unió al lobby {1}..
        /// </summary>
        public static string LogLobbyJoined {
            get {
                return ResourceManager.GetString("LogLobbyJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador {0} salió del lobby {1}.
        /// </summary>
        public static string LogLobbyLeft {
            get {
                return ResourceManager.GetString("LogLobbyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo al notificar estado a un suscriptor..
        /// </summary>
        public static string LogPresenceCallbackFailed {
            get {
                return ResourceManager.GetString("LogPresenceCallbackFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador {0} conectado al servicio Presence.
        /// </summary>
        public static string LogPresenceConnected {
            get {
                return ResourceManager.GetString("LogPresenceConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador {0} desconectado del servicio de presencia..
        /// </summary>
        public static string LogPresenceDisconnected {
            get {
                return ResourceManager.GetString("LogPresenceDisconnected", resourceCulture);
            }
        }
    }
}
