//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConquiánServidor.ConquiánDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConquiánDBEntities : DbContext
    {
        public ConquiánDBEntities()
            : base(GetConnectionString())
        {
        }

        private static string GetConnectionString()
        {
            string envConnection = Environment.GetEnvironmentVariable("CONQUIAN_DB_CONNECTION");

            if (string.IsNullOrEmpty(envConnection))
            {
                throw new InvalidOperationException("CRITICAL ERROR: The environment variable ‘CONQUIAN_DB_CONNECTION’ is not set. For security reasons, the application will not start.");
            }

            return envConnection;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Friendship> Friendship { get; set; }
        public virtual DbSet<Gamemode> Gamemode { get; set; }
        public virtual DbSet<Lobby> Lobby { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<Social> Social { get; set; }
        public virtual DbSet<SocialType> SocialType { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<StatusLobby> StatusLobby { get; set; }
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<GamePlayer> GamePlayer { get; set; }
        public virtual DbSet<LevelRules> LevelRules { get; set; }
    }
}
