//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConquiánServidor.ConquiánDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Social
    {
        public int idSocial { get; set; }
        public string userLink { get; set; }
        public Nullable<int> idPlayer { get; set; }
        public Nullable<int> idSocialType { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual SocialType SocialType { get; set; }
    }
}
